# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e36fac0a76905466adb9224a24c48f775956a4bb12f57564c4b677742d137372a55c299cafdb4dd28fb2bbb62e9661df3650dbb9a6c4f9bb11f78df0aa209374

test:
  secret_key_base: 2cdc8dcd5af62b3faa567863fbd0e4650fd0fe162052c4b61f4f66cdaedb738d028fd7a07f82de444cf576ec5c9894ece75d6d1a91be5cda7536ba505c536907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
